import pandas as pd
dataset_name = 'ign'
df_kw = pd.read_csv('clean_code/Keyword Search Data/Keyword Search Data/kw_dataset_'+dataset_name+'.csv')
df_clf = pd.read_csv('clean_code/Classification Data/bert_dataset_'+dataset_name+'.csv')
s1 = pd.merge(df_kw, df_clf, how='inner', on=['instruction', 'input', 'output'])
leftover_kw_df = pd.concat([s1,df_kw]).drop_duplicates(subset=['instruction', 'input', 'output'],keep=False)
leftover_clf_df = pd.concat([s1,df_clf]).drop_duplicates(subset=['instruction', 'input', 'output'],keep=False)
s1.to_csv('clean_code/Common_Data/bert_dataset_'+dataset_name+'_common.csv')
leftover_kw_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_kw_leftover.csv')
leftover_clf_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_clf_leftover.csv')
print('--------------',dataset_name,'--------------')
print('Len of kw data : ',len(df_kw))
print('Len of clf data : ',len(df_clf))
print('Len of common data : ',len(s1))
print('Len of kw left over data : ',len(leftover_kw_df))
print('Len of clf left over data : ',len(leftover_clf_df))

dataset_name = 'wizardlm'
df_kw = pd.read_csv('clean_code/Keyword Search Data/Keyword Search Data/kw_dataset_'+dataset_name+'.csv')
df_clf = pd.read_csv('clean_code/Classification Data/bert_dataset_'+dataset_name+'.csv')
s1 = pd.merge(df_kw, df_clf, how='inner', on=['instruction', 'output'])
leftover_kw_df = pd.concat([s1,df_kw]).drop_duplicates(subset=['instruction', 'output'],keep=False)
leftover_clf_df = pd.concat([s1,df_clf]).drop_duplicates(subset=['instruction', 'output'],keep=False)
s1.to_csv('clean_code/Common_Data/bert_dataset_'+dataset_name+'_common.csv')
leftover_kw_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_kw_leftover.csv')
leftover_clf_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_clf_leftover.csv')
print('--------------',dataset_name,'--------------')
print('Len of kw data : ',len(df_kw))
print('Len of clf data : ',len(df_clf))
print('Len of common data : ',len(s1))
print('Len of kw left over data : ',len(leftover_kw_df))
print('Len of clf left over data : ',len(leftover_clf_df))

dataset_name = 'dolly'
df_kw = pd.read_csv('clean_code/Keyword Search Data/Keyword Search Data/kw_dataset_'+dataset_name+'.csv')
df_clf = pd.read_csv('clean_code/Classification Data/bert_dataset_'+dataset_name+'.csv')
s1 = pd.merge(df_kw, df_clf, how='inner', on=['instruction', 'context', 'response', 'category'])
leftover_kw_df = pd.concat([s1,df_kw]).drop_duplicates(subset=['instruction', 'context', 'response', 'category'],keep=False)
leftover_clf_df = pd.concat([s1,df_clf]).drop_duplicates(subset=['instruction', 'context', 'response', 'category'],keep=False)
s1.to_csv('clean_code/Common_Data/bert_dataset_'+dataset_name+'_common.csv')
leftover_kw_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_kw_leftover.csv')
leftover_clf_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_clf_leftover.csv')
print('--------------',dataset_name,'--------------')
print('Len of kw data : ',len(df_kw))
print('Len of clf data : ',len(df_clf))
print('Len of common data : ',len(s1))
print('Len of kw left over data : ',len(leftover_kw_df))
print('Len of clf left over data : ',len(leftover_clf_df))

dataset_name = 'alpaca'
df_kw = pd.read_csv('clean_code/Keyword Search Data/Keyword Search Data/kw_dataset_'+dataset_name+'.csv')
df_clf = pd.read_csv('clean_code/Classification Data/bert_dataset_'+dataset_name+'.csv')
s1 = pd.merge(df_kw, df_clf, how='inner', on=['instruction', 'input', 'output'])
leftover_kw_df = pd.concat([s1,df_kw]).drop_duplicates(subset=['instruction', 'input', 'output'],keep=False)
leftover_clf_df = pd.concat([s1,df_clf]).drop_duplicates(subset=['instruction', 'input', 'output'],keep=False)
s1.to_csv('clean_code/Common_Data/bert_dataset_'+dataset_name+'_common.csv')
leftover_kw_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_kw_leftover.csv')
leftover_clf_df.to_csv('clean_code/Leftover_Data/bert_dataset_'+dataset_name+'_clf_leftover.csv')
print('--------------',dataset_name,'--------------')
print('Len of kw data : ',len(df_kw))
print('Len of clf data : ',len(df_clf))
print('Len of common data : ',len(s1))
print('Len of kw left over data : ',len(leftover_kw_df))
print('Len of clf left over data : ',len(leftover_clf_df))
